### ISSUE TITLE
radare2 integration

### ISSUE THREAD

**Issue by XVilka** [letoram/senseye#1]
It would be awesome to integrate this tool with radare2 to provide ability to make your way visually through the massive amount of the raw data or remotely debugged application.

**Comment by letoram** [comment]
Integration with other tools is there on the roadmap, though I hadn't considered radare- as a first target (but that's possibly because I'm usually more debugging oriented than reverse oriented).

I suppose the most reasonable approach (integrating arcan into radares UI would probably be pretty hardcore at the moment, it will be libified, but that's way in the future) would be to have radare act as a sensor / data provider similarly to what fsense is doing now. I'll look into to it (if no-one else beats me to it), but there are a few higher priorities at the moment (3d execution call graphing and more configurable coordinate/data/color mapping).

**Comment by XVilka** [comment]
@letoram thank you for your answer! And if you need something special (or something to fix) from the radare2 side - feel free to ask/suggest that to us/me/radare's issues page.
