### ISSUE TITLE
Issues disabled on arcan

### ISSUE THREAD

**Issue by mewmew** [letoram/senseye#15]
May I ask why issue tracking is disabled on arcan?

Some issues posted in the senseye issue tracker are not strictly related to senseye, which is but a user of arcan.

If the reason is to keep all issues related to senseye *and* arcan in one place, I can fully understand. Then I'd suggest adding a notice in the arcan readme, so users of arcan know where to report issues.

**Comment by letoram** [comment]
Mostly because I dislike of the Github issue tracker, as it doesn't fit my workflow very well. When I code, I usually disable most kinds of distractions, particularly the web. I want my issue tracker as part of git damnit :-)
But I see your point and since I won't take time to set anything else up, I'll unlock it again.
