### ISSUE TITLE
Public discussion channel for ideas any all things related to these projects

### ISSUE THREAD

**Issue by mewmew** [letoram/senseye#16]
@letoram, you are working on some very interesting projects. I feel quite certain that there are a few people within the open source community who would like to discuss ideas related to these projects, both arcan, but in particular senseye.

It would be lovely if this project started using a communication channel for public discussions. If it has already, pardon my ignorance, and please let me know where to join the discussions :)

Potential communication platforms may be
* Gitter
* Slack
* IRC
* ...

Personally, I've grown attached to Gitter, since it has a very low threshold to join discussions, and also integrates well with GitHub activity. Anyone with a GitHub account can simply sign in without having to create a new user account, and the channels have predictable names (i.e. gitter.im/user/repo of the corresponding github.com/user/repo).

Slack works, and also have a lot of integrations with GitHub. I find it a bit slow, as it makes heavy use of javascript, but that may be just me.

IRC have many advantages, core among which is its distributed nature. I don't know how well it integrates with GitHub or if it may be configured to use OAuth with GitHub logins.

Whichever channel of communication, it would be lovely to start a public discuss about ideas and brainstorm collectively :)

Also, if I understood correctly, you are doing a PhD on these topics. When did you start with the research, and how many years of dedicated time do you have left to work on these projects? It would be very interesting indeed to read your paper, once it has been published. Once again, if it has already been published, forgive my ignorance. I'd love to take a look.

Cheers /u

**Comment by letoram** [comment]
There's an IRC channel (#arcan) on Freenode, if that ever gets too busy for the senseye related things we'll split into arcan-senseye etc. and I am, of course, more than open to collaboration. 

The Ph.D was finished years ago (2013), you can find it on http://www.diva-portal.org/smash/record.jsf?pid=diva2%3A834593&dswid=-8752 but it was financed by a EU research project (INTEGRAL) on SmartGrids, which means that I had to sneak in work on the project the best I could on the side rather than it playing a big role in the dissertation, unfortunately. Senseye is really the project I prefer to work on, but the others have been a sort of mix between synergy and a necessary evil.

**Comment by mewmew** [comment]
> The Ph.D was finished years ago (2013), you can find it on http://www.diva-portal.org/smash/record.jsf?pid=diva2%3A834593&dswid=-8752 but it was financed by a EU research project (INTEGRAL) on SmartGrids, which means that I had to sneak in work on the project the best I could on the side rather than it playing a big role in the dissertation, unfortunately.

Thanks for the link to your paper! I didn't realize you were building it for SCADA systems. I truly feel for you, having reviewed such systems in the past, I can only imagine the pains you may have suffered during the project.

In either case, I'm happy you managed to sneak in work on Senseye as it is indeed an interesting project, with huge potential!

Out of curiosity, are you still living in Blekinge were you did the Ph.D.? Give me a ping if you ever happen to be near Stockholm or Uppsala :)

Glada hälsningar /u

**Comment by letoram** [comment]
The wounds have almost, almost healed to the point that I can talk about the memories from working on SCADA (within NDA scope) but yes, it's not something you chose voluntarily if you're not oblivious when going in ;-)

I left Blekinge as soon as I could, Malmö is my homebase these days, so if you ever feel the need to go Skåne... Otherwise, I tend to go to Stockholm to refresh- my social circle around those parts so enjoing some kind of beverage in Uppsala is entirely possible. Think the next visit will happen 'sometime in August'.

**Comment by mewmew** [comment]
> The wounds have almost, almost healed to the point that I can talk about the memories from working on SCADA (within NDA scope) but yes, it's not something you chose voluntarily if you're not oblivious when going in ;-)

Haha, I feel you. I have started a support group for victims of this industry called SDA (SCADA Developers Anonymous). The anonymity of group members is paramount, as they may otherwise be presented with SCADA related job offers that may cause a serious relapses and have a dramatic effect on their health and well-being.

> I left Blekinge as soon as I could, Malmö is my homebase these days, so if you ever feel the need to go Skåne... Otherwise, I tend to go to Stockholm to refresh- my social circle around those parts so enjoing some kind of beverage in Uppsala is entirely possible. Think the next visit will happen 'sometime in August'.

We have some wonderful cafés in Uppsala, if you haven't had a chance to visit them yet. Sometime in August is my favourite time a year :)
